Adds a graph concept to the kustomization detail page
fluxcd/webui pull request #15
Opened 2021-03-18 18:17 UTC by jpellizzari

Adds an initial graph concept. This will need to be re-worked and styled in the future.

![Screenshot from 2021-03-18 11-16-19](https://user-images.githubusercontent.com/2802257/111676460-6bbbf600-87db-11eb-8528-8987e9145735.png)

2021-03-18 23:09 UTC, bia approved these changes
LGTM!
Looking forward to styling this and deep linking each node in the graph to its appropriate page.

Sometimes the graph loads off-centre, it gets fixed if I reload the page : 
<img width="1199" alt="Screenshot 2021-03-19 at 00 07 08" src="https://user-images.githubusercontent.com/92439/111709104-51b7fd00-8847-11eb-8e3f-50d834c92741.png">

2021-03-19 07:04 UTC, bia commented
..and why not add the full graph to each source detail page?

2021-03-19 08:00 UTC, stefanprodan requested changes
A dependency graph should list a tree based on Kustomization.spec.dependsOn. Can we please change the name to something else?

2021-03-19 15:58 UTC, jpellizzari commented
Change from "Dependency Graph" to "Graph"

2021-03-19 16:11 UTC, jpellizzari commented
> ..and why not add the full graph to each source detail page?

We don't know which kustomizations the source applies to, so we can't get the data to draw the graph

2021-03-19 21:41 UTC, stefanprodan commented
I don’t understand what this does, are we displaying the Kubernetes objects reconciled by a Kustomization? If so then many things are missing, like service accounts, rbac, services, network policies, etc

2021-03-19 21:42 UTC, stefanprodan requested changes

2021-03-19 21:42 UTC, stefanprodan commented on ui/components/DependencyGraph.tsx
> +function DependencyGraph({ className, nodes, edges }: Props) {
Why is this called dependency graph?

2021-03-22 16:49 UTC, jpellizzari commented
@stefanprodan 
> I don’t understand what this does, are we displaying the Kubernetes objects reconciled by a Kustomization? If so then many things are missing, like service accounts, rbac, services, network policies, etc

The PR description says "initial concept" because this will probably change drastically. I expect the topology, styling and location of this visualization to change in the near future. As of this PR, it gives us a baseline to work with to make this graph more useful and complete before release.

The intent of this type of visualization is to explain relationships between objects, build trust, and potentially provide contextual navigation.

2021-03-22 16:53 UTC, jpellizzari commented on ui/components/DependencyGraph.tsx
> +function DependencyGraph({ className, nodes, edges }: Props) {
Fixed

2021-03-22 17:29 UTC, stefanprodan commented
@jpellizzari wouldn't be better to render the dependency graph based on `dependsOn`? Listing the objects reconciled by a Kustomization without pagination is not going to work, people have hundreds or event thousands of objects in a repo.

2021-03-22 18:12 UTC, jpellizzari commented
> the dependency graph based on dependsOn

@stefanprodan My understanding is that would be render-able 

> @jpellizzari wouldn't be better to render the dependency graph based on `dependsOn`?

@stefanprodan My understand of the `DependsOn` field is that it would illustrate a different type of relationship between kustomizations. 

The story I am trying to tell with this visualization is "here are all of your flux objects and the resulting k8s objects that were created".

> Kustomization without pagination is not going to work, people have hundreds or event thousands of objects in a repo

Good call out; would it be viable to scope the graph down to object type and namespace? I am imagining an selector that switches between "Deployments, StatefulSet, ServiceAccount" being shown on the graph.

2021-03-22 19:29 UTC, stefanprodan commented
@jpellizzari can you please use https://github.com/fluxcd/flux2-kustomize-helm-example I think one important thing to show in such a graph are are all the kustomizations and helmreleases that originate from the main one, keep in mind that's common to have thins like `kustomization:flux-system -> k:infra + k:apps -> hr:infra + hr:apps -> kube:workloads` and so on.

2021-03-23 14:34 UTC, jpellizzari commented
Created a follow up issue here: https://github.com/fluxcd/webui/issues/16

2021-03-26 09:35 UTC, stefanprodan approved these changes
LGTM

I would changed the title to "Workloads graph" to make it obvious that HelmReleases and any other Flux CR is not displayed here.

2021-03-29 18:31 UTC, merged